# yml template to dockerise a node.js app
version: '3'
services: 
    appservice: 
        container_name: gebirgecontainer
        #build: .
        image: maschroder/image
        
        ports: 
            - '4000:3000'
        depends_on: 
            - mongoservice
    mongoservice:
        container_name: mongo 
        image: mongo # image retrieved from docker hub
        ports:
            - '27017:27017'
        volumes:
            #- ./mongo-init/:/docker-entrypoint-initdb.d/:ro
            - ./mongo-volume:/data/db
    mongoexpressservice: 
        image: mongo-express # image retrieved from docker hub
        restart: always
        ports: 
            - '8081:8081'
        depends_on: 
            - mongoservice